### ISSUE TITLE
MIMIC III- help with data columns

### ISSUE THREAD

**Issue by benbastaki** [nalinimsingh/HST.953#3]
Hi, 
I know this might not be classified as an issue but as I am new to the github not sure how I can request following information.

1. How I can correctly calculate the age of the patient please in MIMIC III?

2. Why 'dob' is something in future? e.g. year 2102?

3. and is DOD mean date of death? if it is I did try to calculate the age (age = DOD - DOB) but some subjects have age 141years?! not sure why?

4. in admission table there is a column called 'diagnosis'. is this mean that patient is diagnosed (reason why he/she is admitted to the Hospital) before the admission to the hospital, or it is diagnosed when he/she was in the hospital?

Your help is much appreciated.

**Comment by matthieukomorowski** [comment]
Hi,

This is probably not the best place to get help about MIMIC-III. Try there instead: https://github.com/MIT-LCP/mimic-code/issues

All your questions are addressed on the MIMIC-III website. You'll find the answers in the database documentation : https://mimic.physionet.org (the website seems to be down at the moment but I'm sure it's only temporary).

Good luck,
Matthieu
